---
- name: Install Apache.
  hosts: all
  become: true

  vars:
   apache_package: apache2
   apache_service: apache2

  handlers:
   - name: restart apache
     service:
      name: "{{ apache_service }}"
      state: present

  pre_tasks:
   - name: Override Apache vars for Red Hat.
     set_fact:
      apache_package: httpd
      apache_service: httpd
     when: ansible_os_family = 'RedHat'

  tasks:
   - name: Ebsure Apache is installed.
     package:
      name: "{{ apache_package }}"
      state: present

   - name : Copy a web page.
     copy:
      content: |
       <html>
       <head><title>Hello Ratko</title></head>
       <body>Zdravo zdravo</body>
       </html>
      dest: "/var/www/html/index.html"
     notify: restart_apache

   - name: Ensure Apache is running
     service:
      name: "{{ apache_service }}"
      state: started
      enabled: true
