---
- name: Converge
  hosts: all
  gather_facts: false
  tasks:
    - name: Update apt cache (on Debian).
      apt:
       update_cache: true
       cache_valid_time: 3600
      when: ansible_os_family == 'Debian'

- import_playbook: /mnt/d/ansib/chap8/molcule-playbook/main.yml
     
